//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankomatSimulator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bankomat1Entities : DbContext
    {
        public bankomat1Entities()
            : base("name=bankomat1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banche> Banches { get; set; }
        public virtual DbSet<Banche_Funzionalita> Banche_Funzionalita { get; set; }
        public virtual DbSet<ContiCorrente> ContiCorrentes { get; set; }
        public virtual DbSet<Funzionalita> Funzionalitas { get; set; }
        public virtual DbSet<Movimenti> Movimentis { get; set; }
        public virtual DbSet<Utenti> Utentis { get; set; }
    }
}
